language: android
android:
  components:
    - build-tools-26.0.0
    - android-23
    - extra-android-m2repository
    - extra-android-support
    - sys-img-armeabi-v7a-android-23
before_install:
  - chmod +x gradlew
script:
  - ./gradlew assembleRelease